logging:
  console:
    enabled: true # default true
    filter:
      level: "DEBUG" # TRACE/DEBUG/INFO/WARN/ERROR; absent = no level filter
  file:
    enabled: false
    path: "orkester.log"
    filter:
      source: "orkester_plugin.*"
plugins:
  dir: ./docker/plugins # directory to scan for .so plugin files
  recursive: false # scan sub-directories?
servers:
  rest_api:
    component:
      plugin: orkester-plugin-core
      server: axum-rest-server
    enabled: true
    port: 8080
    metrics_target: metrics
  metrics:
    component:
      plugin: orkester-plugin-core
      server: metrics-server
    rest_server: rest_api
    enabled: true
  workspace:
    component:
      plugin: orkester-plugin-core
      server: workspace-server
    enabled: true
    rest_target: rest_api
    metrics_target: metrics
    loaders:
      - type: local
        dir: /orkester/docker/samples
  workflows:
    component:
      plugin: orkester-plugin-core
      server: workflows-server
    enabled: true
    rest_target: rest_api
    metrics_target: metrics
    # How often the scheduler checks for due Crons (seconds).
    scheduler_interval_seconds: 30
