logging:
  console:
    enabled: true # default true
    filters:
      - level: "DEBUG"
      - source: "orkester_plugin_core::.*"
        level: "INFO"
      - source: "orkester_plugin_core::servers"
        level: "WARN"
      - source: "orkester::management"
        level: "ERROR"
  file:
    enabled: false
    path: "orkester.log"
    filters:
      - source: "orkester_plugin.*"
plugins:
  dir: /orkester/plugins # directory to scan for .so plugin files
  recursive: false # scan sub-directories?
servers:
  rest_api:
    component:
      plugin: orkester-plugin-core
      server: axum-rest-server
    enabled: true
    port: 8080
    metrics_target: metrics
    statics:
      - url_prefix: /ui
        dir: /orkester/ui
        filters:
          - extension: ["html", "css", "js", "png", "jpg", "jpeg", "gif", "svg"]
        headers:
          Cache-Control: "no-cache"
  metrics:
    component:
      plugin: orkester-plugin-core
      server: metrics-server
    rest_server: rest_api
    enabled: true
  workspace:
    component:
      plugin: orkester-plugin-core
      server: workspace-server
    enabled: true
    rest_target: rest_api
    metrics_target: metrics
    loaders:
      - type: local
        dir: /orkester/samples
  workflows:
    component:
      plugin: orkester-plugin-core
      server: workflows-server
    enabled: true
    rest_target: rest_api
    metrics_target: metrics
    scheduler_interval_seconds: 30
    persistence:
      type: file-persistence
      root-dir: /orkester/data/workflows
