apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orkester.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orkester.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Values.config | toYaml | nindent 4 }}
