{{- if .Values.rbac.create }}
{{- if .Values.rbac.clusterScoped }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "orkester.fullname" . }}
  labels:
    {{- include "orkester.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "orkester.fullname" . }}
  labels:
    {{- include "orkester.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "orkester.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "orkester.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- else }}
{{- $fullname := include "orkester.fullname" . }}
{{- $saName := include "orkester.serviceAccountName" . }}
{{- $releaseNamespace := .Release.Namespace }}
{{- range .Values.rbac.allowedNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $fullname }}
  namespace: {{ . }}
  labels:
    {{- include "orkester.labels" $ | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $fullname }}
  namespace: {{ . }}
  labels:
    {{- include "orkester.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $fullname }}
subjects:
  - kind: ServiceAccount
    name: {{ $saName }}
    namespace: {{ $releaseNamespace }}
{{- end }}
{{- end }}
{{- end }}
